version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/back-server
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 3000
      runas: ubuntu
  
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 3000
      runas: ubuntu

  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 3000
      runas: ubuntu
